// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/21/2024, 4:00:56 PM
const configMerger = require("C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/plugins/**/*.{js,ts,mjs}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/composables/**/*.{js,ts,mjs}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/utils/**/*.{js,ts,mjs}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Amin-Hdn/Desktop/vue3/iran-broker/app.config.{js,ts,mjs}"] }));

module.exports = config
